### PR TITLE
Implement playing song from queue

### PR DESCRIPTION
**Pull request by rrabargos**
I have implemented playing from URI in queue. :)

### CODE REVIEW

**Comment by juan518munoz** [comment]
Please share a video demoing the function.

**Comment by rrabargos** [comment]
Sure! Here it is: https://youtu.be/JsC6JaXQIss

**Review by juan518munoz — APPROVED** [review]
Great work

**Comment by juan518munoz** [comment]
What console api was used to achieve this?

**Comment by rrabargos** [comment]
I piggybacked from context returned in playback state and on user's queue api to produce queue songs uri list and reused your start playlist function (because i saw start playback api also accepts song uri as offset). :)

Responsiveness on watch UI has ways to go. I might need to check if we can have different logic on updating player state

**Pull request merged**
